(function() {var implementors = {};
implementors["tower_h2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Error.html\" title=\"struct tower_h2::Error\">Error</a>&gt; for <a class=\"struct\" href=\"tower_h2/client/struct.Error.html\" title=\"struct tower_h2::client::Error\">Error</a>",synthetic:false,types:["tower_h2::client::connection::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Reason.html\" title=\"struct tower_h2::Reason\">Reason</a>&gt; for <a class=\"struct\" href=\"tower_h2/client/struct.Error.html\" title=\"struct tower_h2::client::Error\">Error</a>",synthetic:false,types:["tower_h2::client::connection::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Error.html\" title=\"struct tower_h2::Error\">Error</a>&gt; for <a class=\"enum\" href=\"tower_h2/client/enum.HandshakeError.html\" title=\"enum tower_h2::client::HandshakeError\">HandshakeError</a>",synthetic:false,types:["tower_h2::client::connection::HandshakeError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Data.html\" title=\"struct tower_h2::Data\">Data</a>&gt; for <a class=\"struct\" href=\"https://docs.rs/bytes/0.4.12/bytes/bytes/struct.Bytes.html\" title=\"struct bytes::bytes::Bytes\">Bytes</a>",synthetic:false,types:["bytes::bytes::Bytes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"tower_h2/struct.Data.html\" title=\"struct tower_h2::Data\">Data</a>&gt; for <a class=\"struct\" href=\"https://docs.rs/bytes/0.4.12/bytes/bytes/struct.BytesMut.html\" title=\"struct bytes::bytes::BytesMut\">BytesMut</a>",synthetic:false,types:["bytes::bytes::BytesMut"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
